### PR TITLE
Improve readability and quality of the Searching page

### PR DESCRIPTION
**Pull request by abcbuck**
This is a big update as I'm reading the manual myself, correcting it wherever I find appropriate.
Large parts of this page have been unreadable, filled with redundant information and UNHELPFUL *formatting*, redundant information, missing, and falsely falsely double words. I'm certain the page could still be improved upon.

In more detail:
- correct style according to the style guide (https://github.com/notepad-plus-plus/npp-usermanual/blob/master/CONTRIBUTION.md)
  - especially `use code formatting` instead of *cursive* or CAPS when writing about `inputs`
- improve symbols used
- improve wording
- improve capitalization
- improve punctuation
- remove checkboxes (☐) where the respective menu has radio buttons (unfortunately there is no good radio button symbol)
- add checkboxes (☐) where appropriate
- correct falsely described functionality
  - right clicking the swap button in the search menu is pointless, however there is a dropdown menu)
  - pressing `Alt` in the find window doesn't highlight any menu items as everything is highlighted with regards to `Alt` functionality already, however pressing `Alt` outside of the find window highlights the regular menu
- insert line breaks for readability
- improve formatting
- get rid of *unnecessary* HIGHLIGHTING
- remove editorial comments confusing the reader ~; maybe because they don't belong in a manual?~
- add links to other parts of the manual when relevant
- correct imprecise/dead links
- delete redundant paragraphs
- update 'collapse' to 'fold' which is the term currently used by Notepad++
- correct menu item spelling
- correct spelling in general
- group character classes by type
- change the order of documentation at sensible points

### CODE REVIEW

**Comment by pryrt** [comment]
> right clicking the swap button in the search menu is pointless, however there is a dropdown menu)

Did you even read the section you are incorrectly correcting?  "v8.5.1 extends this swap feature: you can right click... v8.5.2 added a pulldown-indicator".  This manual describes more than one version, and as such, both sets of descriptions need to exist.  It probably should have said "replaced the right click with a pulldown-indicator" to be more clear, but the basic information is accurate

I looked at a little bit of your changes, but not a huge amount -- but even in there.  In general, unless you already have the full support and permission of the team behind this manual (or any open source project), doing huge, sweeping changes in a single PR is a horrible idea, and will most likely be rejected (as this one will be) for being too difficult to review.  This PR did not follow two of the first four bullets in [CONRIBUTION.md](https://github.com/notepad-plus-plus/npp-usermanual/blob/master/CONTRIBUTION.md), and as such, is being rejected.  

It's sad, because there probably was a bunch of stuff in the PR that would have been accepted if it had been broken up into chunks so that each _small-and-simple_ group of related changes could be easily reviewed, and if the more major changes had used an Issue first, to make sure that we were on the same page before you put in a lot of effort into something that we don't agree about.

**Comment by alankilborn** [comment]
@abcbuck Here's a big hint:  If you (or someone else) tries to view all of your commits at one time, and github says "Can't display large diff" (or whatever exactly it says), then your PR has gone "too far".  As @pryrt says, keep PRs smaller and easily reviewable, even if it means waiting to do further PRs until initial ones are accepted.

**Comment by abcbuck** [comment]
Thank you for the feedback, @pryrt, @alankilborn.
As you may have guessed, I'm new to open source collaboration, so I'm willing to put in an effort to understand how I went wrong here, and retry.
It seems to me, I underestimated the amount of effort needed to review this pull request. To be exact: I thought the number of changed lines (additions and deletions) above the diff was the number of changed *characters*. No wonder it's too much like this.
But no problem. I'm going to split this up into many small PRs, so you don't have to review everything at once.

---

Now for a bit of "counter-"feedback. :)

@pryrt This might come as a surprise to you, but yes, I read the section I incorrectly corrected. Glad you noticed. :) Mistakes happen. Don't take it personally. :)
You seem a bit on the negative side and not exactly welcoming any more contributions - but it's okay. Everyone can have a bad day. :)

About creating an issue first: You know, I'm not doing this purely out of compassion for my favorite editor. As I wrote, I'm currently in the process of reading the manual to better understand the editor myself, and I honestly didn't like a lot of what I've been reading, for the reasons stated above; but I don't complain about them, I try to make things better.
Proceeding like this, I first changed everything that disturbed me; then categorized afterwards what I had changed. So if there was an issue, it would look pretty much exactly the same as this PR because I didn't go out to correct every neatly describable category by itself. Maybe you think an issue could look different, but then again, what do I know what you think...? :)
I think it would be more helpful (or at the very least easier to digest) if you focused on what I need to know instead of blowing it up with destructive rhetoric, including the part of your response that I read. It's easy to get the impression you're more interested in explaining me to be wrong than pointing out what it actually was that could be improved. I get it: I'm a despisable idiot and should just leave you. Now, that that's settled, how about I try again?

I know issues are mentioned in the contribution guidelines which (surprise) I read before opening the PR: "It is best if there is an open [issue](https://github.com/notepad-plus-plus/npp-usermanual/issues) before making changes and submitting a PR, so that you can ask whether your idea is worth incorporating before spending the effort on." - But I already know my objections are worth the effort - hence I don't need to ask if they are.
And you admit to this: A lot of my changes would have been and will be accepted.

And even though never mentioning this you vehemently disagree with me about the inadequacy of checkboxes as a visual indicator for radio buttons, it seems to have struck a nerve leading you to single-handedly edit the contribution guidelines to make sure everyone agrees with you. :)
But who am I to question a well-coordinated group of editors? Forgive me, for I know nothing.

**Comment by alankilborn** [comment]
> I'm willing to put in an effort to understand how I went wrong here, and retry

Good luck.  I think there was a lot of good changes in what you submitted, so I think you'll be successful with smaller submissions.  And the user manual will become better because of it.

>creating an issue first

This is more of a "general plan".  You sort of outline what you think needs doing, and others comment.  If what you're describing isn't welcome, you'll be told so before you put time and effort into it.

> seem a bit on the negative side and not exactly welcoming any more contributions

I don't think this is the case.  "Owners" have a hard and mostly thankless job, and when someone attempts to foist a huge amount of work on them (review work in this case), they can seem a little "testy" in a denial response.  (Just try writing some _code_ for Notepad++ if you really want to see this -- haha).

>But who am I to question a well-coordinated group of editors?

Nah, we're really just like you.  People with spare time and a bit of passion for Notepad++, donating some of that spare time to try to make things better.

**Pull request closed without merging**
