### PR TITLE
Optimized PNG files, removed unused files

### PR DESCRIPTION
**Pull request by tiagofilipesilva**
The PNG files were lossless optimized;
Removed unused files as requested by @donho.

### CODE REVIEW

**Review by donho — CHANGES_REQUESTED** [review]
`content/docs/images/flags/fNorway (1).png` was added by accident.
Just delete `content/docs/images/flags/fNorway (1).png` please.

**Comment by tiagofilipesilva** [comment]
@donho
There is also an XML file in the flag folder.

**Comment by donho** [comment]
@tiagofilipesilva 
> There is also an XML file in the flag folder, I'm not sure if that is needed.

Please delete the xml file in the flag folder as well.

**Review by donho — APPROVED** [review]

**Comment by donho** [comment]
@pryrt  Could you merge it please?

**Pull request merged**
