### PR TITLE
Add title and reorder menu

### PR DESCRIPTION
**Pull request by donho**
The new system will use the `weight` to order the menu.

### CODE REVIEW

**Comment by MetaChuh** [comment]
as we don't have a hugo or jeckyll engine preview yet, it would be unwise to judge the outcome, without being able to view it, except by predicting it, simulating the theoretical order outcome, based on it's weight.

@milipili 
please contact me in private, as i will not be able to make a valid review without your help.

**Comment by milipili** [comment]
This is designed for gohugo. Temporary, you can take any hugo template locally. Sorry I am quite busy at work recently with some major internal release, but soon we will have a deployment per merge request as it should be.

**Comment by donho** [comment]
@MetaChuh So can we still consider it as non-blockrd point ?
I don't really think these modifications are big deal. It'll be great if we can move forward.

**Comment by milipili** [comment]
LGTM

**Comment by MetaChuh** [comment]
@milipili 

splendid that it looks good to you 😉

i need your help to see the same on local hugo (55.6)
do you have some template files and hugo command line to render the md structure for me ?

they are not within this repo yet, and every member will need to be able to render every pr, in order to be able to validate each pr.

many thanks.

**Pull request merged**
