### PR TITLE
clarify Darken Inactive Tabs

### LINKED ISSUE #714: Clarify "Preferences/General/Tab Bar/Darken inactive tabs" interaction with "Style Configurator/Global Styles/Inactive tabs/Background color"
DISCLAIMER: The following only considers non-Dark mode of Notepad++.

---

Current user manual entry:  `Darken inactive tabs: Change the fill-color on inactive tabs to a darker color.`

Suggested improvement:

`Darken inactive tabs: Change the background on inactive tabs to the color configured for _Global Styles_ > _Inactive tabs_ > _Background color_.  Note: If this is setting is not enabled, the chosen background color for inactive tabs will be ignored and will be the same as the active tab's background color.`

---

Current user manual entry:  `Inactive tabs [background and foreground] ⇒ Selects the color to be used for the filename displayed in the titlebars of all inactive tabs.`

Suggested improvement:

`Inactive tabs [background and foreground] ⇒ Foreground: selects the color to be used for the filename text displayed in all inactive tabs.  Background: selects the color to be used to fill in the background of all inactive tabs (note: for the background  setting to affect the tabs, 'Darken inactive tabs' in Preferences > General must be enabled).`

### PR DESCRIPTION
**Pull request by pryrt**
closes #714

### CODE REVIEW

**Comment by alankilborn** [comment]
Nice job!

**Comment by alankilborn** [comment]
@pryrt

Afterthoughts...do these deserve documenting:

* When tabs are colored via _View_ (menu) > _Tab_ > _Apply color_ X, then the background color setting for inactive tabs is ignored in favor of the chosen tab coloring.  The active tab color in such a case is no different from an uncolored tab.

* When tabs are colored via _View_ (menu) > _Tab_ > _Apply color_ X, the foreground color setting for _Active tab focused_ and _Active tab unfocused_ are ignored in favor of two colors (a "heavy" one for "focused" and a "lighter" one for "unfocused") derived from the chosen tab coloring.

**Comment by pryrt** [comment]
Would it be sufficient to say "these take precedence over the active and inactive tab color settings"?

**Comment by alankilborn** [comment]
> "these take precedence over the active and inactive tab color settings"

Concise.  I like it.

**Pull request merged**
