### PR TITLE
Documentation fixes

### PR DESCRIPTION
**Pull request by milipili**

### CODE REVIEW

**Comment by donho** [comment]
Cool @milipili !
I let you to merge this PR.

**Comment by donho** [comment]
Merged failed @milipili  ;)

**Comment by milipili** [comment]
piko?

**Comment by donho** [comment]
"Merge pull request #6 from milipili/documentation-fixes"
This commit shouldn't be here.
https://github.com/notepad-plus-plus/npp-usermanual/commits/master

**Pull request merged**
