### PR TITLE
Minor spelling correction

### PR DESCRIPTION
**Pull request by LGFN**
1. witch = which
2. Replaced comma (,) with period (.)

### CODE REVIEW

**Review by pryrt — APPROVED** [review]
Thanks

**Comment by LGFN** [comment]
Please excuse my lack of expertise in git, but is there anything else need to be done in order this change should go live?

**Comment by pryrt** [comment]
On the next release of the user manual, which is likely to be a week or so after NPP v7.9.6 releases

**Comment by sasumner** [comment]
@donho Is a PR such as this governed by the "tourist" policy, or maybe that doesn't apply because this is the manual?

**Comment by donho** [comment]
@sasumner 
>  Is a PR such as this governed by the "tourist" policy, or maybe that doesn't apply because this is the manual?

For me such policy doesn't apply to manual - there's no code but only document.
However, we (members who manage this project) can still have a consensus for such policy.

**Comment by pryrt** [comment]
@sasumner , excuse my ignorance, but what's the "tourist policy"?

**Comment by sasumner** [comment]
@pryrt Sorry for not explaining.  It's Don's policy of not accepting a PR (for code) where someone fixes a typo with possible motivation of getting their name in the "contributor's list", apparently for résumé-padding purposes ("Look at me, I wrote code for Notepad++!").  It's okay to create an issue pointing out a misspelling/typo, but regular devs will fix such things themselves.  Don appears to be asking if we think that policy should be extended to manual as well.  I agree with that, but I don't see myself fixing such typos :-)

**Comment by pryrt** [comment]
@sasumner , Thanks for the explanation.

I cannot imagine résumé-padding being as much of an issue for a usermanual repo, except maybe for technical writers. ;-)

If we start getting lots of these typo-PR submissions, maybe I'll change my tune.  But for now, I don't have a problem reviewing these.  But I'll go with consensus if others want to disallow such PR.

**Pull request merged**
