### PR TITLE
Describe the config-file locations as per-user and machine-wide

### LINKED ISSUE #399: config file locations: machine vs per-user explanation
Alan suggested something akin to https://community.notepad-plus-plus.org/post/79576 be added to the User Manual.

### PR DESCRIPTION
**Pull request by pryrt**
Better explain the difference between the two, and when it will fall back to machine-wide closes #399

### CODE REVIEW

**Comment by pryrt** [comment]
@alankilborn, does this look like what you were hoping for?

**Comment by alankilborn** [comment]
>does this look like what you were hoping for?

Looks good; I learned some stuff.
It was a bit hard to look thru the diff with all the whitespace changes.

**Comment by alankilborn** [comment]
I found the setting for ignoring whitespace; then the change of the bulleting symbol stood out as changes.  At least that wasn't SO burdensome to see.

**Comment by pryrt** [comment]
Sorry, I shouldn't've included the bullet and whitespace changes.  That was a bad decision on my part.

**Pull request merged**
