### PR TITLE
"Nimrod" -> "Nim" (language was renamed 2014)

### PR DESCRIPTION
**Pull request by trustable-code**

### CODE REVIEW

**Comment by sasumner** [comment]
So this would rename it in the documentation, but what about in the actual program; some occurrences there:

image

image

image

**Comment by trustable-code** [comment]
Ok, this should be changed too, unfortunately I have no idea how this works in the Notepad++ source code.

**Comment by sasumner** [comment]
>Ok, this should be changed too, unfortunately I have no idea how this works in the Notepad++ source code.

Can you open an issue regarding it in the N++ code site?  You can link over here, tying the 2 things together.

**Review by pryrt — APPROVED** [review]
Looks good, since notepad-plus-plus/notepad-plus-plus#9768 was fixed, I will merge this one, too

**Pull request merged**
