### PR TITLE
Irish language binary translation

### PR DESCRIPTION
**Pull request by jignasa06**
Hello,
Greetings of the day!!
@chcg , @donho

We have submitted Irish language binary translation on 30th January 2020 and we got a reply from @donho on 31st January 2020 as don said "Your Irish localization file will be included in the next release. Thank you for your contribution."

Here is a screenshot of email reply
https://prnt.sc/rqbeg4

We have seen Irish language binary translation which is already added in notepad++ directory, here is the screenshot
https://prnt.sc/rqbnrr

Also, we have checked the binary translation page on the notepad++ site (https://npp-user-manual.org/docs/binary-translation/) but not found Irish translation files on this page.
A
Also, we have attached Irish flag

we are looking forward to hearing back from you

Thank you

### CODE REVIEW

**Comment by jignasa06** [comment]
@chcg , @donho Would you please look into this matter?

**Comment by chcg** [comment]
@jignasa06 To have the flag also visible on the webpage you need to modify also https://github.com/notepad-plus-plus/npp-usermanual/blob/master/content/docs/binary-translation.md and add a link to the image and https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/irish.xml
see also:
https://raw.githubusercontent.com/notepad-plus-plus/npp-usermanual/master/content/docs/binary-translation.md

So you need to add:

```
<div align="center" style="margin: 20px; display: inline-block;">
<a href="https://github.com/notepad-plus-plus/notepad-plus-plus/blob/master/PowerEditor/installer/nativeLang/irish.xml" target="_blank"><img src="/docs/images/flags/fIrish.png" alt="" border="0" /><br /> Irish</a> 
</div>

```

**Comment by donho** [comment]
@chcg  I think @jignasa06 is talking about this page:
https://npp-user-manual.org/docs/binary-translation/

Do you confirm, @jignasa06  ?

**Comment by donho** [comment]
@chcg  I will take care of it.

**Comment by jignasa06** [comment]
@donho  So you will do it by yourself? I mean you will add Irish flag on the binary translation page, right? or would you please guide us so we can do it. let me know on which file we need to do a modification.

**Comment by donho** [comment]
@jignasa06  I will ask people (Irish native speakers) to review it. I will be back to you when the review is done.

**Comment by jignasa06** [comment]
Thank you for your reply

**Comment by donho** [comment]
Irish translation has been removed via the commit:
https://github.com/notepad-plus-plus/notepad-plus-plus/commit/e9e9e8daa92b14091dfde930dca8af406d162fe9

Please check the following link for the information:
https://github.com/notepad-plus-plus/notepad-plus-plus/pull/8273

**Pull request closed without merging**
