### PR TITLE
Document reverse line order feature

### PR DESCRIPTION
**Pull request by debiedowner**
Implements #216

### CODE REVIEW

**Comment by sasumner** [comment]
@pryrt Please let me review this one.  I'm assigning it to myself.

**Comment by sasumner** [comment]
@debiedowner 

I had some offline discussion with the Notepad++ author about this feature and we decided to make this change of location for the menu entry:

image

We decided to move the "random sort" as well, and change its text slightly, so the sum total of all changes will appear like this:

image

Because this was my suggestion, and my code to change it (in https://github.com/notepad-plus-plus/notepad-plus-plus/pull/9868 ), I'll take over finishing the documentation for all of this.

So I'm going to close your PR without acceptance.
Sorry for the wasted time you went through to create it.
But...and this is important:  Thank you for providing user manual input for your code change.

**Comment by debiedowner** [comment]
@sasumner Makes sense, neither are actually sorts; I only placed it there to follow the precedent of "Sort Lines Randomly". I initially even considered naming it "Sort Lines Reversely" to fit in with the others, but it makes even less sense than the 'randomly' one, as it is even less of a sort, being dependent on the existing line order. So instead I considered renaming the 'randomly' item exactly like you suggest, though I didn't, to keep my pull request as minimal as possible.

**Comment by sasumner** [comment]
@debiedowner 

Yep, sometimes an addition makes something else not "fit right".  I think that's the case here.  But...we then make an adjustment to make the evolution better.

**Pull request closed without merging**
